# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=50)),
                ('password_salt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MCAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MCResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('position', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=50)),
                ('password_salt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='mcresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Question'),
        ),
        migrations.AddField(
            model_name='mcresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.MCAnswer'),
        ),
        migrations.AddField(
            model_name='mcresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Student'),
        ),
        migrations.AddField(
            model_name='mcanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerapp.Section'),
        ),
    ]
