# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-19 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='section',
        ),
        migrations.RemoveField(
            model_name='textresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='game',
        ),
        migrations.RemoveField(
            model_name='question',
            name='position',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TextResponse',
        ),
    ]
